spring.application.name=sistema-voos

# ==========================================
# CONFIGURAÇÃO DO POSTGRESQL LOCAL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/meuvoo
spring.datasource.username=postgres
spring.datasource.password=2006
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
# Usa o dialeto correto para traduzir o SQL para o Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# O 'update' cria as tabelas automaticamente e nunca apaga seus dados
spring.jpa.hibernate.ddl-auto=update

# Mostrar o SQL no console para debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true