spring.application.name=sistema-voos

# ==========================================
# CONFIGURAÇÃO DO BANCO DE DADOS (DINÂMICO)
# ==========================================
# Se estiver no Render, ele pega a URL da nuvem. Se estiver local, usa o localhost.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meuvoo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:2006}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Ative o show-sql para termos certeza absoluta se ele vai fazer os INSERTS
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true